# Generated by Django 4.1.1 on 2023-05-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('name', models.CharField(blank=True, choices=[('servicio publicos', 'Servicio Publicos'), ('alimentos', 'Alimentos'), ('ropa', 'Ropa'), ('salud', 'Salud'), ('educacion', 'Educacion'), ('tecnologia', 'Tecnologia'), ('transporte', 'Transporte'), ('vivienda', 'Vivienda'), ('otros', 'Otros')], max_length=200)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
