# Generated by Django 4.1.1 on 2023-05-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_categories_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=12, null=True),
        ),
    ]
